In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
columns = [
    "id", "diagnosis",
    "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean",
    "compactness_mean", "concavity_mean", "concave_points_mean", "symmetry_mean", "fractal_dimension_mean",

    "radius_se", "texture_se", "perimeter_se", "area_se", "smoothness_se",
    "compactness_se", "concavity_se", "concave_points_se", "symmetry_se", "fractal_dimension_se",

    "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst",
    "compactness_worst", "concavity_worst", "concave_points_worst", "symmetry_worst", "fractal_dimension_worst"
]

In [3]:
df= pd.read_csv("/content/wdbc.data", names=columns)

In [4]:
df.shape

(569, 32)

In [5]:
df.drop("id",axis=1,inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [7]:
x=df.drop(columns=["diagnosis"])
y=df["diagnosis"]

In [8]:
x.shape

(569, 30)

In [9]:
y.shape

(569,)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler=StandardScaler()

In [16]:
x_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
logistic=LogisticRegression()

In [35]:
logistic.fit(x_scaled,y_train)

LogisticRegression()

In [36]:
logistic.classes_

array(['B', 'M'], dtype=object)

In [37]:
y_predict=logistic.predict_proba(x_test_scaled)

In [38]:
y_predict

array([[8.86409750e-01, 1.13590250e-01],
       [9.00936206e-06, 9.99990991e-01],
       [3.07909541e-03, 9.96920905e-01],
       [9.99489866e-01, 5.10134225e-04],
       [9.99939361e-01, 6.06389713e-05],
       [9.48088275e-11, 1.00000000e+00],
       [1.53672652e-09, 9.99999998e-01],
       [3.49030633e-02, 9.65096937e-01],
       [6.20657860e-01, 3.79342140e-01],
       [9.99240597e-01, 7.59402734e-04],
       [9.50128217e-01, 4.98717826e-02],
       [1.24071210e-02, 9.87592879e-01],
       [9.93926181e-01, 6.07381873e-03],
       [1.43930883e-01, 8.56069117e-01],
       [9.98378244e-01, 1.62175599e-03],
       [7.40182295e-04, 9.99259818e-01],
       [9.98147541e-01, 1.85245908e-03],
       [9.99988834e-01, 1.11662359e-05],
       [9.99999182e-01, 8.18375684e-07],
       [1.11701472e-06, 9.99998883e-01],
       [9.15836610e-01, 8.41633901e-02],
       [9.90252217e-01, 9.74778299e-03],
       [4.33732406e-09, 9.99999996e-01],
       [9.99921081e-01, 7.89186669e-05],
       [9.988612

In [39]:
y_predict[:,-1]

array([1.13590250e-01, 9.99990991e-01, 9.96920905e-01, 5.10134225e-04,
       6.06389713e-05, 1.00000000e+00, 9.99999998e-01, 9.65096937e-01,
       3.79342140e-01, 7.59402734e-04, 4.98717826e-02, 9.87592879e-01,
       6.07381873e-03, 8.56069117e-01, 1.62175599e-03, 9.99259818e-01,
       1.85245908e-03, 1.11662359e-05, 8.18375684e-07, 9.99998883e-01,
       8.41633901e-02, 9.74778299e-03, 9.99999996e-01, 7.89186669e-05,
       1.13874333e-03, 5.84587240e-04, 1.07444521e-03, 5.97518345e-03,
       2.85311713e-03, 9.99991817e-01, 5.17409813e-04, 1.48760128e-04,
       2.16094439e-03, 5.49413839e-03, 1.40706288e-04, 2.42334266e-03,
       9.42415985e-01, 2.89870352e-03, 9.99911214e-01, 4.81363757e-02,
       7.12433090e-05, 9.99593392e-01, 2.46640626e-03, 9.63884505e-04,
       1.99892051e-02, 7.15547342e-02, 3.98571939e-04, 4.90625569e-04,
       3.04698010e-02, 6.14016147e-04, 9.99879654e-01, 9.99999947e-01,
       3.08211520e-01, 1.32293769e-02, 2.73627242e-05, 9.54524359e-03,
      

In [25]:
type(y_predict)

numpy.ndarray

In [60]:
threshold=0.1

In [61]:
y_pred_custom = (y_predict[:, -1] >= threshold).astype(int)

In [62]:
y_pred_custom

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1])

In [63]:
from sklearn.metrics import *

In [64]:
Y_pred = pd.DataFrame(y_pred_custom, columns=['diagnosis'])

In [65]:
Y_pred['diagnosis']=Y_pred['diagnosis'].map({1:'M',0:'B'})

In [66]:
confusion_matrix(y_test,Y_pred)

array([[64,  7],
       [ 1, 42]])

In this step, we explored adjusting the classification threshold in the Logistic Regression model to reduce false negatives (FN), which is critical in medical datasets like breast cancer detection.

By default, the model uses a threshold of 0.5 to convert predicted probabilities into class labels. To gain more control over predictions, we used `predict_proba()` to extract the probability of the positive class (Malignant) and applied custom thresholds (0.5 and 0.1).

The goal was to reduce false negatives, as missing a malignant case is more serious than a false alarm.

However, after evaluation using the confusion matrix:
- At threshold = 0.5 → FN = 1
- At threshold = 0.1 → FN = 1

We observed that lowering the threshold did not reduce false negatives. Instead, it increased false positives.

This indicates that the misclassified malignant case had a very low predicted probability, meaning the model was highly confident but incorrect. In such cases, threshold tuning alone cannot fix the issue.

Conclusion:
Threshold adjustment is effective only for borderline cases (probabilities near the decision boundary). Since our false negatives were not borderline, this method did not improve model performance. Therefore, we retain the default threshold (0.5) and explore other techniques like class weighting to further reduce false negatives.